---
apiVersion: v1
kind: Service
metadata:
  name: service-security-server-sidecar-primary
  labels:
    run: service-security-server-sidecar-primary
  namespace: sidecar
spec:
  clusterIP: None
  selector:
    run: security-server-sidecar-primary
---
