apiVersion: v1
kind: Service
metadata:
  name: balancer-security-server-sidecar
  annotations:
    service.beta.Kubernetes.io/aws-load-balancer-type: nlb
  labels:
    run: balancer-security-server-sidecar
  namespace: sidecar
spec:
  type: LoadBalancer
  selector:
    run: security-server-sidecar-secondary
  ports:
  - port: 5500
    targetPort: 5500
    protocol: TCP
    name: messaging
  - port: 5577
    targetPort: 5577
    protocol: TCP
    name: ocsp
    name: tcp-5577
  - port: 4000
    targetPort: 4000
    protocol: TCP   
    name: https
