---
apiVersion: v1
kind: Secret
metadata:
  name: secret-ssh-keys
  namespace: sidecar
type: Opaque
data:
  public-key: public-key.pub
  private-key: private-key
---

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-sidecar-variables
  namespace: sidecar
type: Opaque
stringData:
  XROAD_TOKEN_PIN: "secret"
  XROAD_ADMIN_USER: "xrd"
  XROAD_ADMIN_PASSWORD: "secret"
  XROAD_DB_HOST: "INFO"
  XROAD_DB_PWD: "postgres"
  XROAD_DB_PORT: "5432"
  XROAD_LOG_LEVEL: "Logs"
  XROAD_DATABASE_NAME: "dbpostgres"
---
