apiVersion: v1
kind: Service
metadata:
  name: xroad-service-sidecar
spec:
  selector:
    run: security-server-sidecar-primary
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer